---
title: "Gpr88 - draft1"
output: html_document
---

```{r message=FALSE, warning=FALSE, tidy=TRUE}
library(tidyr)
library(dplyr)
library(ggplot2)
setwd("~/Desktop/brainRNASeq/InteractiveApps/Interactive_graph")
factorize <- function(df){
	# This function is to change the experiment column to factor and relevel accordingly
	df$experiment <- as.factor(df$experiment)
  df$experiment <- factor(df$experiment,levels = c("WT-control", 
  																								 "WT-light_induced", 
  																								 "Per1-control", 
  																								 "Per1-light_induced"))
  return(df)
}


# read in the data table with the normalized count data from each brain region
countData_SCN <- read.csv("SCN_count_ready_for_plot.csv", header = TRUE, 
													stringsAsFactors = FALSE)
countData_VTA <- read.csv("VTA_count_ready_for_plot.csv", header = TRUE, 
													stringsAsFactors = FALSE)
countData_LHb <- read.csv("LHb_count_ready_for_plot.csv", header = TRUE, 
													stringsAsFactors = FALSE)
countData_NAc <- read.csv("NAc_count_ready_for_plot.csv", header = TRUE, 
													stringsAsFactors = FALSE)

# relevel the experiment column for each dataframe
countData_SCN <- factorize(countData_SCN)
countData_VTA <- factorize(countData_VTA)
countData_LHb <- factorize(countData_LHb)
countData_NAc <- factorize(countData_NAc)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, tidy = TRUE, fig.height=7, fig.width=5}

countDataPlot_SCN <- countData_SCN[countData_SCN$mgi_symbol %in% "Gpr88", ]
p <- ggplot(countDataPlot_SCN, aes(x=experiment, y = counts)) 
p <- p + geom_boxplot() + geom_point() 
p <- p + ggtitle("SCN") + xlab(" ") + ylab("Normalized counts")
p <- p + theme(text = element_text(size=16),
								axis.title.y = element_text(size=16),
                axis.text.x = element_text(angle=90, vjust=0.5, size=16),
								axis.text.y = element_text(size=16),
								panel.background = element_rect(fill = NA),
								axis.line = element_line(size = 0.8, colour = "black"),
								axis.ticks = element_line(size = 1)) 
print(p)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, tidy = TRUE, fig.height=7, fig.width=5}
countDataPlot_VTA <- countData_VTA[countData_VTA$mgi_symbol %in% "Gpr88", ]
p2 <- ggplot(countDataPlot_VTA, aes(x=experiment, y = counts)) 
p2 <- p2 + geom_boxplot() + geom_point()
p2 <- p2 + ggtitle("VTA") + xlab(" ") + ylab("Normalized counts")
p2 <- p2 + theme(text = element_text(size=16),
								axis.title.y = element_text(size=16),
                axis.text.x = element_text(angle=90, vjust=0.5, size=16),
								axis.text.y = element_text(size=16),
								panel.background = element_rect(fill = NA),
								axis.line = element_line(size = 0.8, colour = "black"),
								axis.ticks = element_line(size = 1)) 
print(p2)
```
  
```{r echo=FALSE, message=FALSE, warning=FALSE, tidy = TRUE, fig.height=7, fig.width=5}
countDataPlot_LHb <- countData_LHb[countData_LHb$mgi_symbol %in% "Gpr88", ]
p3 <- ggplot(countDataPlot_LHb, aes(x=experiment, y = counts)) 
p3 <- p3 + geom_boxplot() + geom_point()
p3 <- p3 + ggtitle("LHb") + xlab(" ") + ylab("Normalized counts")
p3 <- p3 + theme(text = element_text(size=16),
								axis.title.y = element_text(size=16),
                axis.text.x = element_text(angle=90, vjust=0.5, size=16),
								axis.text.y = element_text(size=16),
								panel.background = element_rect(fill = NA),
								axis.line = element_line(size = 0.8, colour = "black"),
								axis.ticks = element_line(size = 1)) 
print(p3)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, tidy = TRUE, fig.height=7, fig.width=5}
countDataPlot_NAc <- countData_NAc[countData_NAc$mgi_symbol %in% "Gpr88", ]
p4 <- ggplot(countDataPlot_NAc, aes(x=experiment, y = counts)) 
p4 <- p4 + geom_boxplot() + geom_point()
p4 <- p4 + ggtitle("NAc") + xlab(" ") + ylab("Normalized counts")
p4 <- p4 + theme(text = element_text(size=16),
								axis.title.y = element_text(size=16),
                axis.text.x = element_text(angle=90, vjust=0.5, size=16),
								axis.text.y = element_text(size=16),
								panel.background = element_rect(fill = NA),
								axis.line = element_line(size = 0.8, colour = "black"),
								axis.ticks = element_line(size = 1)) 
print(p4)
```

```{r}
sessionInfo()
```