---
title: "LHb all comparsion TopGO(Biological process) analysis"
output: html_document
---

```{r message=FALSE, warning=FALSE, tidy=TRUE}
library(topGO)
library(dplyr)
library(tidyr)
library(genefilter)

# Prepare the list of gene of interest and the list of the background

# set working directory
setwd("~/Desktop/brainRNASeq/R_analysis/R_output/results_tables/")

# read in the file with the normalized data
result <- read.csv("LHb/LHb_all_comparsion.csv", header = TRUE, 
									                              stringsAsFactors = FALSE)
result$remark <- as.factor(result$remark)

# subset the genes of interest
gene.of.interest <- result[(result$remark %in% "significant") | 
													 	(result$remark %in% "significant & more than 1-fold"),]

# remove duplicated rows
gene.of.interest <- unique(gene.of.interest)

# define the gene background
# remove duplicated rows with different mgi_symbol but the same ensembl_gene_id
duplicate.row <- result[duplicated(result$ensembl_gene_id), ]
duplicate.row.list <- as.numeric(rownames(duplicate.row))
result.unique <- result[- duplicate.row.list, ]

rownames(result.unique) <- result.unique$ensembl_gene_id

gene.of.interest.list <- gene.of.interest$ensembl_gene_id
gene.of.interest.list <- unique(gene.of.interest.list)

overall.base.mean <- as.matrix(result.unique[,"baseMean", drop = F])
gene.background <- genefinder(overall.base.mean, gene.of.interest.list, 
															10, method = "euc")
gene.background <- rownames(overall.base.mean)[as.vector(sapply(gene.background, 
																																function(x)x$indices))]
gene.background <- setdiff(gene.background, gene.of.interest$ensembl_gene_id)

gene.universe.list <- unique(c(gene.background, gene.of.interest.list))

gene.list <- factor(as.integer(gene.universe.list %in% gene.of.interest.list))
names(gene.list) <- gene.universe.list
```

```{r fig.height=6, fig.width=8, message=FALSE, warning=FALSE, tidy=TRUE}

library(RColorBrewer)
library(cancerTiming)

all.gene <- log2(result.unique$baseMean)
gene.selected <- log2(result.unique[gene.of.interest$ensembl_gene_id,"baseMean"])
background <- log2(result.unique[gene.background, "baseMean"])

multidensity(list(all = all.gene, fore = gene.selected, back = background),
             xlab="log2 mean counts", main = "Matching for enrichment analysis")

legend("topright", legend = c("All gene", "Gene of interest","background"), 
                   col = c("black","green","red"),
                   lwd=1)
```

```{r message=FALSE, warning=FALSE, tidy=TRUE}
GO.data <- new ("topGOdata", ontology ="BP", allGenes = gene.list, 
								annot=annFUN.org, mapping="org.Mm.eg.db", ID = "ensembl")

# perform the classic Fisher test
fisher.test <- runTest(GO.data, algorithm = "classic", statistic = "Fisher")
# perform the  elim Fisher test
elim.fisher.test <- runTest(GO.data, algorithm = "elim", statistic = "Fisher")
# perform the  using classic KS test
KS.test <- runTest(GO.data, algorithm = "classic", statistic = "ks")
# perform the using elim KS test
elim.KS.test <- runTest(GO.data, algorithm = "elim", statistic = "ks")


fisher.result <- GenTable(GO.data, classicFisher = fisher.test,
													         elimFisher = elim.fisher.test,
													         classicKS = KS.test,
													         elimKS = elim.KS.test, 
                                   ranksOf = "classicFisher",
													         topNodes = 10)

elim.fisher.result <- GenTable(GO.data, elimFisher = elim.fisher.test,
															          classicFisher = fisher.test,
															          classicKS = KS.test,
															          elimKS = elim.KS.test,
															          ranksOf = "elimFisher",
															          topNodes = 10)

KS.result <- GenTable(GO.data, classicKS = KS.test,
															 classicFisher = fisher.test,
															 elimFisher = elim.fisher.test,
															 elimKS = elim.KS.test, 
                               ranksOf = "classicKS",
															 topNodes = 10)

elim.KS.result <- GenTable(GO.data, elimKS = elim.KS.test,
													          classicFisher = fisher.test,
													          elimFisher = elim.fisher.test,
													          classicKS = KS.test,
													          ranksOf = "elimKS",
													          topNodes = 10)
```

```{r fig.height=10, fig.width=8, message=FALSE, warning=FALSE, tidy=TRUE}
par(cex = 0.6)
showSigOfNodes(GO.data, score(fisher.test), firstSigNodes = 5, useInfo = "all")
```

```{r fig.height=10, fig.width=8, message=FALSE, warning=FALSE, tidy=TRUE}
par(cex = 0.6)
showSigOfNodes(GO.data, score(elim.fisher.test), firstSigNodes = 5, useInfo = "all")
```

```{r fig.height=8, fig.width=8, message=FALSE, warning=FALSE, tidy=TRUE}
par(cex = 0.6)
showSigOfNodes(GO.data, score(KS.test), firstSigNodes = 5, useInfo = "all")
```

```{r fig.height=8, fig.width=8, message=FALSE, warning=FALSE, tidy=TRUE}
par(cex = 0.6)
showSigOfNodes(GO.data, score(elim.KS.test), firstSigNodes = 5, useInfo = "all")
```

```{r}
setwd("~/Desktop/brainRNASeq/R_analysis/R_output/topGO/LHb/")
saveRDS(GO.data,"BP/LHb_all_comparsion_topGO_BP.RData")
write.csv(fisher.result, "BP/LHb_all_comparsion_BP_fisher.csv", row.names = FALSE)
write.csv(elim.fisher.result, "BP/LHb_all_comparsion_BP_elimfisher.csv", row.names = FALSE)
write.csv(KS.result, "BP/LHb_all_comparsion_BP_KS.csv", row.names = FALSE)
write.csv(elim.KS.result, "BP/LHb_all_comparsion_BP_elimKS.csv", row.names = FALSE)
```

```{r}
sessionInfo()
```